[package]
name = "tokio-budget-chat"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stream = "0.3.0"
bytes = "1"
itertools = "0.10.5"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
